version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
     - "POSTGRES_USER=root"
     - "POSTGRES_DB=label_automobile"
    volumes:
     - "./data/:/var/lib/postresql/data"
    ports:
     - "5432:5432"
